apiVersion: v1
kind: Service
metadata:
  name: {{ include "BasicHotelApiChart.fullname" . }}
  labels:
{{ include "BasicHotelApiChart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "BasicHotelApiChart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
