apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: basichotelapi-pod                            # 2
  labels:
    app: basichotelapi
spec:                                                # 3
  containers:
    - image: basichotelapi-v1           			 # 4
      name: basichotelapi-container                  # 5
      imagePullPolicy: Never
      ports:
        - containerPort: 80                          # 6