apiVersion: v1
kind: Service              # 1
metadata:
  name: basichotelapi-debug-lb
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 8085             # 3
    protocol: TCP          # 4
    targetPort: 80         # 5
  selector:                # 6
    app: basichotelapi-debug     # 7